### ISSUE TITLE
Incomplete string text too light to read

### ISSUE THREAD

**Issue by alexkrolick** [finico/vscode-theme-sunrise#3]
I like this theme a lot (is it based on something or original?) but I have an issue where invalid or incomplete bits of text become too light to read until the error is resolved. For example...

There's an `I` at the end of the line, but it's too light to read until the ending quote is added:

<img width="363" alt="screen shot 2016-12-04 at 9 29 23 pm" src="https://cloud.githubusercontent.com/assets/1571667/20874658/d49ad2c6-ba68-11e6-9339-ebfa14be4ec1.png">

**Comment by finico** [comment]
@alexkrolick thank you for report!
I'm glad you like it.

> is it based on something or original?

It's based on my original theme for Intellij IDE. [Intellij Sunrise Theme](https://github.com/finico/intellij-finico-color-schemes/blob/master/finico-sunrise.icls)

> invalid or incomplete bits of text become too light to read until the error is resolved.

I'll fix it asap.

**Comment by finico** [comment]
vscode is not supported background for "invalid" scope..
Yet it's all that is possible:

<img width="401" alt="screen shot 2016-12-05 at 12 29 36" src="https://cloud.githubusercontent.com/assets/4924283/20879845/9d358802-bae6-11e6-8dc2-77cc09712378.png">

<img width="401" alt="screen shot 2016-12-05 at 12 37 19" src="https://cloud.githubusercontent.com/assets/4924283/20880101/a0824f3a-bae7-11e6-868e-466d03d3e2af.png">
